Addressed error on Bukkit shutdown with disable-permission-system due to parameter mismatch.
Error info:

SEVERE] Error occurred while disabling cljminecraft v1.0.3 (Is it up to
date?)
clojure.lang.ArityException: Wrong number of args (0) passed to:
core$disable-permission-system